name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  tests-and-coverage-pip:
    name: Test & Coverage (pip)
    uses: ./.github/workflows/reusable_test_pip.yml
    with:
      use_latest_pytorch_gpytorch: true
    secrets: inherit
